- name: configuring the {{COMPONENT}} repo
  ansible.builtin.copy:
    src: mongo.repo
    dest: /etc/yum.repos.d/mongodb.repo

- name: install {{COMPONENT}}
  ansible.builtin.package:
    name: mongodb-org
    state: present

- name: configuring service name to server
  ansible.builtin.shell: "set-hostname {{COMPONENT}}-{{ENV}}"

