# ansible -i inv all -e ansible_username=centos -e ansible_password=DevOps321 -m shell -a uptime
# -m : module -i: inventory -a: arugumnet
# To run the playbook: ansible-playbook -i inv -e ansible_user=centos -e ansible_password=DevOps321 01-playbook.yml
- name: play1
  hosts: all
  tasks:
    - name: printing hi from task1 of play1
      ansible.builtin.debug:
       msg: "Hi from play1 of task"  
    - name: printing hi from task2 of play1
      ansible.builtin.debug:
       msg: "Devops learning"  

- name: play2
  hosts: all
  tasks:
    - name: printing hi from play2
      ansible.builtin.debug:
       msg: "message printing from play2" 