# To run the script: ansible-playbook -i inv -e ansible_user=centos -e ansible_password=DevOps321 -e ENV=prod 02-vars.yml
# argument variable > local variable > global variable : priority
- name: Demo on variable using in playbook
  hosts: all
  vars:
    URL: global.variable.com   
  vars_files:
    # - dev.yml
    - "{{ENV}}.yml" # argument input while running the script
  vars_prompt:
    - name: URNAME
      prompt: what is your name?
      private: false 
  tasks:
    - name: printing Global variable
      ansible.builtin.debug:
        msg: URL is "{{URL}}"
    - name: printing argument Variable
      ansible.builtin.debug:
        msg: URL is {{URL}} # argument variable 
    - name: printing Local Variable
      ansible.builtin.debug:
        msg: URL is {{URL}}
      vars:
        URL: local.variable.com
    - name: printing use of prompt input
      ansible.builtin.debug:
        msg: My name is {{URNAME}}
    - name: using files and get the input
      ansible.builtin.debug:
        msg: type of INSTANCE is {{INSTANCE_TYPE}}
      
    
      

  