- name: Demo on variable using in playbook
  hosts: all
  vars:
    URL: play.google.com
  vars_files:
    - dev.yml
  vars_prompt:
    - name: URNAME
      prompt: what is your name?
      private: false
  tasks:
    - name: printing Global variable
      ansible.builtin.debug:
        msg: URL is "{{URL}}"
    - name: printing argument Variable
      ansible.builtin.debug:
        msg: URL is {{URL}}
    - name: printing Local Variable
      ansible.builtin.debug:
        msg: URL is {{URL}}
      vars:
        URL: task.google.com
    - name: printing use of prompt input
      ansible.builtin.debug:
        msg: My name is {{URNAME}}
    - name: using files and get the input
      ansible.builtin.debug:
        msg: type of INSTANCE is {{INSTANCE_TYPE}}
      
    
      

  