- name: Demo on variable using in playbook
  hosts: all
  vars:
    URL: play.google.com
  tasks:
    - name: printing Global variable
      ansible.builtin.debug:
        msg: URL is "{{URL}}"
    - name: printing argument Variable
      ansible.builtin.debug:
        msg: URL is {{URL}}
    - name: printing Local Variable
      ansible.builtin.debug:
        msg: URL is {{URL}}
      vars:
        URL: task.google.com
    
      

  