#if you want provide root access then you need provide 'become: yes'

- name: Prividing privilige acces
  hosts: all
  tasks:
    - name: checking user id
      ansible.builtin.shell: id
      register: OUT #printing the shell output you need to register first
    - name: print output value
      ansible.builtin.debug:
        msg: Uptime value is {{OUT}} 
    

    