- name: install nginx
  ansible.builtin.package:
    name: nginx
    state: present

- name: download and extract 
  ansible.builtin.unarchive:
    src: https://github.com/stans-robot-project/frontend/archive/main.zip
    dest: /tmp/frontend.zip
    remote_src: yes